name: SonarCloud Analysis

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=syazantri_tutorial-1
            -Dsonar.organization=syazantri